### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Bailey-24** [columbia-ai-robotics/fit2form#2]
Hi, I ran `python main.py --mode grasp_objects`

I got this 
`Traceback (most recent call last):
  File "main.py", line 61, in <module>
    create_grasp_objects(*setup(args, config))
  File "/run_code/fit2form-master/generate_data.py", line 29, in create_grasp_objects
    urdf_paths = urdf_paths * ceil(total * 1.5 / len(urdf_paths))
ZeroDivisionError: float division by zero`

I have placed the `data/ShapeNetCore.v2` dataset in the project.
My computer is Ubuntu18.04, Nvidia MX150

I would appreciate it if you would help me. Thanks in advanced.

**Comment by submagr** [comment]
This issue should be fixed after following steps in my comment here:

https://github.com/columbia-ai-robotics/fit2form/issues/1#issuecomment-1078552207
