### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_categories.txt'

### ISSUE THREAD

**Issue by Bailey-24** [columbia-ai-robotics/fit2form#3]
Hi, @submagr ,
I finally generated all the grasp objects and datasets which the network needed.

But when I pretrain autoencoder, 
`python main.py --name train_ae --mode vae --train data/train_categories.txt --val data/val_categories.txt --shapenet_train_hdf data/ShapeNetCore.v2/shapenet_grasp_results_train.hdf5 --shapenet_val_hdf data/ShapeNetCore.v2/shapenet_grasp_results_val.hdf5`

I got this error,
```pybullet build time: Oct  8 2020 00:10:46
SEEDING WITH 0
2022-03-29 22:03:58,470 INFO resource_spec.py:212 -- Starting Ray with 16.41 GiB memory available for workers and up to 8.22 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2022-03-29 22:03:58,863 INFO services.py:1170 -- View the Ray dashboard at 127.0.0.1:8265
configs/default.json [Logger] logging to  runs/train_ae/
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    train_vae(*setup_train_vae(args, config))
  File "/hy-tmp/fit/fit2form-master/utils.py", line 430, in setup_train_vae
    finger_tsdf_paths=glob_category(args.objects, args.train, "**/model_normalized_*_imprint_*_tsdf.npy"),
  File "/hy-tmp/fit/fit2form-master/utils.py", line 400, in glob_category
    with open(category_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_categories.txt'
```

Even though I manually add the `train_categories.txt` or `val_categories.txt` in the data folder. (nothing in the train_catagories.txt)
I got the error as below.

```
pybullet build time: Oct  8 2020 00:10:46
SEEDING WITH 0
2022-03-29 22:16:47,998 INFO resource_spec.py:212 -- Starting Ray with 16.41 GiB memory available for workers and up to 8.22 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2022-03-29 22:16:48,369 INFO services.py:1170 -- View the Ray dashboard at 127.0.0.1:8265
configs/default.json
[Logger] logging to  runs/train_ae/
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    train_vae(*setup_train_vae(args, config))
  File "/hy-tmp/fit/fit2form-master/utils.py", line 438, in setup_train_vae
    train_vae_datasets.append(VAEDatasetHDF(dataset_path=args.shapenet_train_hdf,))
  File "/hy-tmp/fit/fit2form-master/learning/utils.py", line 588, in __init__
    assert Path(dataset_path).exists()
AssertionError
```

I also try my best to solve the problem, but my skill is not very well. So would you please give me some tips about what content in the `train_catagories.txt`. Thanks in advanced.

By the way, I found that we should run some mode before generate grasp objects.
```
python main.py --mode collision_mesh
python main.py --mode urdf
python main.py --mode grasp_objects
```

And run the 
`python main.py --name "data/imprint_grasp_datsaet/"  --mode imprint_baseline `
before `python main.py --name "data/imprint_grasp_datsaet/" --mode pretrain_imprint_dataset `.

**Comment by submagr** [comment]
Hi @Bailey-24,
I have updated the code addressing your findings. Please pull and follow the instructions in the updated readme.
