### ISSUE TITLE
KeyError: 'optimizers'

### ISSUE THREAD

**Issue by Bailey-24** [columbia-ai-robotics/fit2form#5]
I want to pretrain generator network, use command `python main.py --name pretrain_gn --mode pretrain_gn --ae_checkpoint_path runs/train_ae/vae_099.pth --num_processes=1`
But I got this .
```sh
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    pretrain_gn(args, config)
  File "/run_code/fit2form-master/train.py", line 697, in pretrain_gn
    setup_pretrain(args, config)
  File "/run_code/fit2form-master/utils.py", line 388, in setup_pretrain
    net = setup_network(args, hyperparameters)
  File "/run_code/fit2form-master/utils.py", line 304, in setup_network
    checkpoint_dict={"ae_checkpoint_path": args.ae_checkpoint_path}
  File "/run_code/fit2form-master/learning/gripperDesigner.py", line 122, in __init__
    self.load_ae_checkpoint(checkpoint_dict["ae_checkpoint_path"])
  File "/run_code/fit2form-master/learning/gripperDesigner.py", line 167, in load_ae_checkpoint
    optimizers = checkpoint['optimizers']
KeyError: 'optimizers'
```

**Comment by submagr** [comment]
Hi @Bailey-24,
Can you print `checkpoint.keys()` before line 167. Seems like the model is loaded via checkpoint, but the checkpoint dict does not have optimizers saved for some reason (looking into it)

Meanwhile, you can comment out [these two lines](https://github.com/columbia-ai-robotics/fit2form/blob/master/learning/gripperDesigner.py#L167-L168) since the default optimizer is [already specified in the init function](https://github.com/columbia-ai-robotics/fit2form/blob/master/learning/gripperDesigner.py#L104).

**Comment by submagr** [comment]
Hi @Bailey-24,
I have updated the code addressing your findings. Please pull and follow the instructions in the updated readme.
